apiVersion: v1
kind: Service
metadata:
  name: next-lane-api
  labels:
    app.kubernetes.io/name: next-lane
    app.kubernetes.io/component: api
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: next-lane
    app.kubernetes.io/component: api
  ports:
    - name: http
      port: 4000
      targetPort: http
      protocol: TCP
